<?php 
$mysql_host="localhost";
$mysql_user="opencart";
$mysql_pass="opencarted123459";
$mysql_db="opencart";
$tracker_title="asdfasdf";
$tracker_url_name="livingstonei2p.xyz";
$tracker_url_key="asdf";
$torrent_dir="asdf";
